### ISSUE TITLE
xml_path argument of add_xml looks a bit weird

### ISSUE THREAD

**Issue by jvmf1** [jvmf1/hikvision#8]
I'm thinking of removing this argument and pass the full xml path to `add_{getter,setter}` instead.

@ccutrer What do you think about that?

**Comment by ccutrer** [comment]
🤷 

I don't have strong feelings. It looks a little bit weird, but there are a lot of `add_{getter,setter}` calls that it's reducing repetition on. It's all internal meta-programming, so a bit of weirdness doesn't bother me much.
